In [98]:
import warnings
import pandas as pd
import numpy as np

In [58]:
sigungu_df = pd.read_csv('./sigungu_code.csv', encoding='cp949')
sigungu_df.head()

   시군구코드  법정동코드  행정동코드    시도명 시군구명 법정동명   행정동명     적용시작일     적용만료일
0  11680  10600    675  서울특별시  강남구  대치동   개포3동  20221223  99991231
1  11680  10300    675  서울특별시  강남구  개포동   개포3동  20221223  99991231
2  11680  11400    675  서울특별시  강남구  일원동   개포3동  20221223  99991231
3  11740  10300    525  서울특별시  강동구  상일동  상일제1동  20210701  99991231
4  11740  10300    526  서울특별시  강동구  상일동  상일제2동  20210701  99991231

In [67]:
sigungu_df = sigungu_df[['시군구코드','시군구명']]
sigungu_df = sigungu_df.drop_duplicates()
sigungu_df = sigungu_df.reset_index(drop=True)
sigungu_df = sigungu_df.dropna()
sigungu_df

    시군구코드  시군구명
0   11680   강남구
1   11740   강동구
2   11290   성북구
3   11530   구로구
4   11305   강북구
5   11410  서대문구
6   11500   강서구
7   11440   마포구
8   11710   송파구
9   11230  동대문구
10  11140    중구
11  11110   종로구
12  11350   노원구
13  11620   관악구
14  11590   동작구
15  11560  영등포구
16  11200   성동구
17  11170   용산구
18  11380   은평구
19  11260   중랑구
20  11215   광진구
21  11545   금천구
22  11320   도봉구
23  11650   서초구
24  11470   양천구

In [69]:
sigungu_list = list(sigungu_df['시군구코드'])
sigungu_list

[11680,
 11740,
 11290,
 11530,
 11305,
 11410,
 11500,
 11440,
 11710,
 11230,
 11140,
 11110,
 11350,
 11620,
 11590,
 11560,
 11200,
 11170,
 11380,
 11260,
 11215,
 11545,
 11320,
 11650,
 11470]

In [36]:
import PublicDataReader as pdr

In [105]:
# 오픈 API 서비스키 입력
service_key = "JEzO8dJIlLTP5vOiYpxqEbr1ZWHkAz1cvnJ6EqBp528pB%2FBEbovCkz6jDb8NALCkXIoW7FX0J1%2FlwMOkGkxQlQ%3D%3D"

In [106]:
from PublicDataReader import TransactionPrice as tp
api = tp(service_key)

In [113]:
import pandas as pd
warnings.filterwarnings(action='ignore')

def get_data_for_sigungu(sigungu_code):
    return api.get_data(
        property_type="아파트",
        trade_type="매매",
        sigungu_code=sigungu_code,
        start_year_month="202201",
        end_year_month="202212"
    )

combined_df = pd.concat(map(get_data_for_sigungu, sigungu_list))

Exception: SERVICE KEY IS NOT REGISTERED ERROR.